apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespaces.yaml
  - istio-mtls.yaml
  - karpenter-nodepools.yaml
  - nodelocal-dnscache.yaml

commonLabels:
  app.kubernetes.io/managed-by: ace-platform
