apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
  labels:
    app.kubernetes.io/part-of: garudax-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-ingress
  labels:
    istio-injection: enabled
    app.kubernetes.io/part-of: garudax-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: karpenter
  labels:
    app.kubernetes.io/part-of: garudax-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: garudax-exchange
  labels:
    istio-injection: enabled
    app.kubernetes.io/part-of: garudax-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: garudax-services
  labels:
    istio-injection: enabled
    app.kubernetes.io/part-of: garudax-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: garudax-infra
  labels:
    app.kubernetes.io/part-of: garudax-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: garudax-monitoring
  labels:
    app.kubernetes.io/part-of: garudax-platform
