apiVersion: v1
kind: ConfigMap
metadata:
  name: service-discovery
  namespace: ace-services
data:
  MATCHING_ENGINE_ADDR: "matching-engine.ace-exchange.svc.cluster.local:50051"
  CLEARING_ENGINE_ADDR: "clearing-engine.ace-exchange.svc.cluster.local:50052"
  MARGIN_ENGINE_ADDR: "margin-engine.ace-exchange.svc.cluster.local:50053"
  SETTLEMENT_ENGINE_ADDR: "settlement-engine.ace-exchange.svc.cluster.local:50054"
  AUTH_SERVICE_ADDR: "auth-service.ace-services.svc.cluster.local:50055"
  COMPLIANCE_SERVICE_ADDR: "compliance-service.ace-services.svc.cluster.local:50056"
  MARKET_DATA_SERVICE_ADDR: "market-data-service.ace-services.svc.cluster.local:50057"
  WAREHOUSE_SERVICE_ADDR: "warehouse-service.ace-services.svc.cluster.local:50058"
  GATEWAY_ADDR: "gateway.ace-services.svc.cluster.local:8080"
  POSTGRES_HOST: "postgres.ace-infra.svc.cluster.local"
  POSTGRES_PORT: "5432"
  REDIS_HOST: "redis.ace-infra.svc.cluster.local"
  REDIS_PORT: "6379"
  KAFKA_BROKERS: "kafka-0.kafka-headless.ace-infra.svc.cluster.local:9092,kafka-1.kafka-headless.ace-infra.svc.cluster.local:9092,kafka-2.kafka-headless.ace-infra.svc.cluster.local:9092"
