apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: garudax-infra
  labels:
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/part-of: garudax-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: zookeeper
  ports:
    - name: client
      port: 2181
      targetPort: client
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper-headless
  namespace: garudax-infra
  labels:
    app.kubernetes.io/name: zookeeper
    app.kubernetes.io/part-of: garudax-platform
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: zookeeper
  ports:
    - name: client
      port: 2181
      targetPort: client
    - name: follower
      port: 2888
      targetPort: follower
    - name: election
      port: 3888
      targetPort: election
