apiVersion: v1
kind: ServiceAccount
metadata:
  name: warehouse-service
  namespace: garudax-services
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/garudax-warehouse-service-irsa
  labels:
    app.kubernetes.io/name: warehouse-service
    app.kubernetes.io/part-of: garudax-platform
