apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: matching-engine
  namespace: ace-exchange
  labels:
    app.kubernetes.io/name: matching-engine
    app.kubernetes.io/part-of: ace-platform
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: matching-engine
