apiVersion: v1
kind: ServiceAccount
metadata:
  name: matching-engine
  namespace: ace-exchange
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/ace-matching-engine-irsa
  labels:
    app.kubernetes.io/name: matching-engine
    app.kubernetes.io/part-of: ace-platform
