apiVersion: v1
kind: Service
metadata:
  name: admin-ui
  namespace: garudax-services
  labels:
    app.kubernetes.io/name: admin-ui
    app.kubernetes.io/part-of: garudax-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: admin-ui
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
