apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: garudax-infra
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/part-of: garudax-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: kafka
  ports:
    - name: broker
      port: 9092
      targetPort: broker
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: garudax-infra
  labels:
    app.kubernetes.io/name: kafka
    app.kubernetes.io/part-of: garudax-platform
spec:
  type: ClusterIP
  clusterIP: None
  selector:
    app.kubernetes.io/name: kafka
  ports:
    - name: broker
      port: 9092
      targetPort: broker
