apiVersion: v1
kind: ServiceAccount
metadata:
  name: market-data-service
  namespace: ace-services
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/ace-market-data-service-irsa
  labels:
    app.kubernetes.io/name: market-data-service
    app.kubernetes.io/part-of: ace-platform
