apiVersion: v1
kind: Service
metadata:
  name: clearing-engine
  namespace: garudax-exchange
  labels:
    app.kubernetes.io/name: clearing-engine
    app.kubernetes.io/part-of: garudax-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: clearing-engine
  ports:
    - name: grpc
      port: 50052
      targetPort: grpc
      protocol: TCP
    - name: health
      port: 8082
      targetPort: health
      protocol: TCP
