apiVersion: v1
kind: ServiceAccount
metadata:
  name: gateway
  namespace: ace-services
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/ace-gateway-irsa
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/part-of: ace-platform
