apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: ace-services
  labels:
    app.kubernetes.io/name: gateway
    app.kubernetes.io/part-of: ace-platform
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gateway
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
    - name: health
      port: 8090
      targetPort: health
      protocol: TCP
