apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  # Scale down for dev environment
  - target:
      kind: NodePool
      name: exchange-core-burst
    patch: |
      - op: replace
        path: /spec/limits/cpu
        value: "32"
      - op: replace
        path: /spec/limits/memory
        value: 64Gi

  - target:
      kind: NodePool
      name: app-general-burst
    patch: |
      - op: replace
        path: /spec/limits/cpu
        value: "64"
      - op: replace
        path: /spec/limits/memory
        value: 128Gi

  - target:
      kind: NodePool
      name: data-pipeline-burst
    patch: |
      - op: replace
        path: /spec/limits/cpu
        value: "32"
      - op: replace
        path: /spec/limits/memory
        value: 128Gi
